version: "3.7"
services:

    grafana:
        image: grafana/grafana:6.6.0
        restart: always
        container_name: grafana
        ports:
            - 8080:3000
        volumes:
            - ${PWD}/plugins:/var/lib/grafana/plugins
        environment: 
            GF_SERVER_HTTP_PORT: 3000
            GF_SECURITY_ADMIN_USER: admin
            GF_SECURITY_ADMIN_PASSWORD: admin